# computer vision lab 1

### TASK 1 numpy train

#### 1)

 ***  np.indices تقوم باعطائي  مصفوفة ثلاثية الابعاد تحتوي على قيم الاندكس  ***

In [2]:
import numpy as np
img0 = np.indices((8, 8)).sum(axis=0) % 2
img0 = (img0 * 255).astype(np.uint8)
print("Original 8x8 checkerboard:")
print(img0)

Original 8x8 checkerboard:
[[  0 255   0 255   0 255   0 255]
 [255   0 255   0 255   0 255   0]
 [  0 255   0 255   0 255   0 255]
 [255   0 255   0 255   0 255   0]
 [  0 255   0 255   0 255   0 255]
 [255   0 255   0 255   0 255   0]
 [  0 255   0 255   0 255   0 255]
 [255   0 255   0 255   0 255   0]]


  * There is 2 value is unique and its represent the white and black so its checkboard *

my turn :  i want to make vertical white and black pic : 
note that for horizontal just take the first matrix instead of tow

the main point here is for odd its give 1 and for even its give 2 because the mod of 2 

In [3]:
img1 = np.indices((8,8))[1] %2
img1 = (img1 * 255)
print(img1) 

[[  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]]


#### 2) Kronecker Product.

In [4]:
print(np.ones([2,2]) , ' * ' , img1)

[[1. 1.]
 [1. 1.]]  *  [[  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]
 [  0 255   0 255   0 255   0 255]]


In [5]:
img = img0.copy()
scaled2 = np.kron(img, np.ones((2, 2), dtype=np.uint8))
print(np.ones([2,2]))
print("\nScaled (x2) shape:", scaled2.shape)
print(scaled2)

[[1. 1.]
 [1. 1.]]

Scaled (x2) shape: (16, 16)
[[  0   0 255 255   0   0 255 255   0   0 255 255   0   0 255 255]
 [  0   0 255 255   0   0 255 255   0   0 255 255   0   0 255 255]
 [255 255   0   0 255 255   0   0 255 255   0   0 255 255   0   0]
 [255 255   0   0 255 255   0   0 255 255   0   0 255 255   0   0]
 [  0   0 255 255   0   0 255 255   0   0 255 255   0   0 255 255]
 [  0   0 255 255   0   0 255 255   0   0 255 255   0   0 255 255]
 [255 255   0   0 255 255   0   0 255 255   0   0 255 255   0   0]
 [255 255   0   0 255 255   0   0 255 255   0   0 255 255   0   0]
 [  0   0 255 255   0   0 255 255   0   0 255 255   0   0 255 255]
 [  0   0 255 255   0   0 255 255   0   0 255 255   0   0 255 255]
 [255 255   0   0 255 255   0   0 255 255   0   0 255 255   0   0]
 [255 255   0   0 255 255   0   0 255 255   0   0 255 255   0   0]
 [  0   0 255 255   0   0 255 255   0   0 255 255   0   0 255 255]
 [  0   0 255 255   0   0 255 255   0   0 255 255   0   0 255 255]
 [255 255   0 

the main difference is we make a zoom for the pixsels so the black spot now have 4 pixel and the same for white 

there is 2 unique value and
i see overlabs between the numpers 

the pattern is one pixel have black color and the around of it have the white color and vice versa .

my turn : 

In [6]:
img = img0.copy()
scaled3 = np.kron(img, np.ones((3, 3), dtype=np.uint8))
print("\nScaled (x3) shape:", scaled3.shape)
print(scaled3)


Scaled (x3) shape: (24, 24)
[[  0   0   0 255 255 255   0   0   0 255 255 255   0   0   0 255 255 255
    0   0   0 255 255 255]
 [  0   0   0 255 255 255   0   0   0 255 255 255   0   0   0 255 255 255
    0   0   0 255 255 255]
 [  0   0   0 255 255 255   0   0   0 255 255 255   0   0   0 255 255 255
    0   0   0 255 255 255]
 [255 255 255   0   0   0 255 255 255   0   0   0 255 255 255   0   0   0
  255 255 255   0   0   0]
 [255 255 255   0   0   0 255 255 255   0   0   0 255 255 255   0   0   0
  255 255 255   0   0   0]
 [255 255 255   0   0   0 255 255 255   0   0   0 255 255 255   0   0   0
  255 255 255   0   0   0]
 [  0   0   0 255 255 255   0   0   0 255 255 255   0   0   0 255 255 255
    0   0   0 255 255 255]
 [  0   0   0 255 255 255   0   0   0 255 255 255   0   0   0 255 255 255
    0   0   0 255 255 255]
 [  0   0   0 255 255 255   0   0   0 255 255 255   0   0   0 255 255 255
    0   0   0 255 255 255]
 [255 255 255   0   0   0 255 255 255   0   0   0 255 255 255 

#### 3) rotation

In [7]:
img = img0.copy()
rot90 = np.rot90(img, k=1) # 90 degrees counter-clockwise
print("\nRotated 90°:")
print(rot90)


Rotated 90°:
[[255   0 255   0 255   0 255   0]
 [  0 255   0 255   0 255   0 255]
 [255   0 255   0 255   0 255   0]
 [  0 255   0 255   0 255   0 255]
 [255   0 255   0 255   0 255   0]
 [  0 255   0 255   0 255   0 255]
 [255   0 255   0 255   0 255   0]
 [  0 255   0 255   0 255   0 255]]


now when we rotate image the pic is differance because the last row become the first column and so on 

In [8]:
#todo rotate by 18img = img0.copy()
#note that 90 * 2 = 180
img = img0.copy()
rot180 = np.rot90(img, k=2) 
print("\nRotated 180°:")
print(rot180)


Rotated 180°:
[[  0 255   0 255   0 255   0 255]
 [255   0 255   0 255   0 255   0]
 [  0 255   0 255   0 255   0 255]
 [255   0 255   0 255   0 255   0]
 [  0 255   0 255   0 255   0 255]
 [255   0 255   0 255   0 255   0]
 [  0 255   0 255   0 255   0 255]
 [255   0 255   0 255   0 255   0]]


### Task 2 — Display images (and save outputs)

In [9]:
from PIL import Image
img_pil = Image.open("../data/lenna.png")
print("Pillow:")
print(" size (W,H):", img_pil.size)
print(" mode:", img_pil.mode)

Pillow:
 size (W,H): (512, 512)
 mode: RGB


In [10]:
import cv2
img_cv = cv2.imread("../data/lenna.png") # BGR
print("OpenCV:")
print(" shape (H,W,C):", img_cv.shape)
print(" dtype:", img_cv.dtype)
cv2.imshow("Lenna (OpenCV)", img_cv)
cv2.waitKey(0)
cv2.destroyAllWindows()

OpenCV:
 shape (H,W,C): (512, 512, 3)
 dtype: uint8


In [11]:
#todo : Your turn: load baboon.png with both libraries and print its size/shape.

image_pil = Image.open("../data/baboon.png")
print ("baboon image size  with pilow: ", image_pil.size)
img_cv = cv2.imread("../data/baboon.png")
print("baboon image shape with open cv : ", img_cv.shape)


baboon image size  with pilow:  (512, 512)
baboon image shape with open cv :  (512, 512, 3)


### Task 3 — Convert color (RGB/BGR and grayscale)


In [12]:
gray_pil = img_pil.convert("L")
print("Pillow grayscale mode:", gray_pil.mode)
gray_pil.save("../outputs/lenna_gray_pillow.png")

Pillow grayscale mode: L


In [13]:
gray_cv = cv2.cvtColor(img_cv, cv2.COLOR_BGR2GRAY)
print("OpenCV grayscale shape:", gray_cv.shape)
cv2.imwrite("../outputs/lenna_gray_opencv.png", gray_cv)

OpenCV grayscale shape: (512, 512)


True

In [14]:
rgb_cv = cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB)
cv2.imwrite("../outputs/lenna_rgb_converted_from_opencv.png", rgb_cv)

True

whats the differance between color image and  grayscale array ? 
the main differance is the color image have 3 values (how mush eavery pixel have from (Red , Green and blue ) colors 
nut the gray scale every pixel have only one value its the gray scaled from 0 to 255

In [15]:
#to do : convert baboon.png to grayscale with both libraries.

In [16]:
image_pil = Image.open("../data/baboon.png")
gray_pil = image_pil.convert("L")

In [17]:

img_cv = cv2.imread("../data/baboon.png")
gray_cv = cv2.cvtColor(img_cv, cv2.COLOR_BGR2GRAY)

In [18]:
gray_pil.save("../outputs/baboon_gray_pil.png")
cv2.imwrite("../outputs/baboon_gray_cv.png", gray_cv)

True

### Task 4 — Inspect pixel values

In [19]:
# getpixel uses (x, y)
px00 = img_pil.getpixel((0, 0))
px10 = img_pil.getpixel((1, 0))
print("Pillow pixel (0,0):", px00)
print("Pillow pixel (1,0):", px10)

# OpenCV array indexing is [y, x] and color is BGR
px00_cv = img_cv[0, 0]
px10_cv = img_cv[0, 1]
print("OpenCV pixel [0,0] (BGR):", px00_cv)
print("OpenCV pixel [0,1] (BGR):", px10_cv)


arr_pil = np.array(img_pil)  # RGB
print("NumPy from Pillow shape:", arr_pil.shape)
print("arr_pil[0,0] (RGB):", arr_pil[0, 0])


Pillow pixel (0,0): (226, 137, 125)
Pillow pixel (1,0): (226, 137, 125)
OpenCV pixel [0,0] (BGR): [ 71 150 164]
OpenCV pixel [0,1] (BGR): [31 57 63]
NumPy from Pillow shape: (512, 512, 3)
arr_pil[0,0] (RGB): [226 137 125]


Explain why img_pil.getpixel((x,y)) vs img_cv[y,x] looks “swapped”.
Explain why the color channel order differs.

its swapped because in pilow we use the coordinate (x,y) and in cv we use it as (y,x) 
and the color cannel its swapped between Red and Blue between openCV lib and pilow lib

In [20]:
# todo :  pick a pixel near the center and compare its values in Pillow vs OpenCV.
size = img_pil.size
width = size[0]
hight = size[1]
pxMid = img_pil.getpixel((width //2 , hight//2 ))

print("Pillow pixel of the mid :", pxMid)


# OpenCV array indexing is [y, x] and color is BGR
widthCV = img_cv.shape[0]
hightCV = img_cv.shape[2]

pxmidd_cv = img_cv[hightCV//2, widthCV//2] 
print("OpenCV pixel mid (BGR):", pxmidd_cv)


arr_pil = np.array(img_pil)  # RGB
print("NumPy from Pillow shape:", arr_pil.shape)
print("arr_pil[0,0] (RGB):", arr_pil[width //2,hight//2])


Pillow pixel of the mid : (180, 65, 72)
OpenCV pixel mid (BGR): [ 85 109  75]
NumPy from Pillow shape: (512, 512, 3)
arr_pil[0,0] (RGB): [180  65  72]


### Task 5 (Transformations)

#### 5A) Pillow transformations

In [21]:
# Resize (scale down)
small_pil = img_pil.resize((img_pil.size[0] // 2, img_pil.size[1] // 2))
small_pil.save("../outputs/lenna_small_pillow.png")
# Rotate (degrees, around image center)
rot_pil = img_pil.rotate(30)  # default expands=False
rot_pil.save("../outputs/lenna_rot30_pillow.png")
# Flip left-right
flip_pil = img_pil.transpose(Image.FLIP_LEFT_RIGHT)
flip_pil.save("../outputs/lenna_flip_lr_pillow.png")

##### 5B) OpenCv transformations

In [22]:
h, w = img_cv.shape[:2]
# Resize
small_cv = cv2.resize(img_cv, (w // 2, h // 2))
cv2.imwrite("../outputs/lenna_small_opencv.png", small_cv)
# Rotate 90 degrees (built-in)
rot90_cv = cv2.rotate(img_cv, cv2.ROTATE_90_COUNTERCLOCKWISE)
cv2.imwrite("../outputs/lenna_rot90_opencv.png", rot90_cv)
# Flip: 1=horizontal, 0=vertical, -1=both
flip_cv = cv2.flip(img_cv, 1)
cv2.imwrite("../outputs/lenna_flip_lr_opencv.png", flip_cv)

True

Which library was easier for rotation?
i think pillow is more easyer and more simple than cv2 because the cv2 is spacified for computer vision rather than the pillow 

In [23]:
# todo try a different rotation angle in OpenCV 
# i have to use the open Cv to rotate the picture but the main proplem that opencv want 3 args 
# the center of rotation (in our case its the center  and the angle and the scale of zoom (if you dont want to zoom make it by 1 ))
# i decide to take 127 degree 
# first we need to make the rotation matrix and determine the center : 
h, w = img_cv.shape[:2]
center = (w/2 , h/2)

rot127_cv = cv2.getRotationMatrix2D(center, 127, 1.0)
rotated = cv2.warpAffine(img_cv, rot127_cv, (w, h))

cv2.imshow("Rotated", rotated)
cv2.waitKey(0)

-1

### Task6 (drowing)

In [24]:
from PIL import ImageDraw, Image
img = Image.open("../data/lenna.png")
img_draw_pil = img.copy()
draw = ImageDraw.Draw(img_draw_pil)
# Rectangle: [(x0,y0), (x1,y1)]
draw.rectangle([(50, 50), (200, 200)], outline="red", width=3)
# Line: [(x0,y0), (x1,y1)]
draw.line([(0, 0), (img_draw_pil.size[0]-1, img_draw_pil.size[1]-1)], fill="yellow", 
width=3)
# Text
draw.text((60, 210), "Lab 1", fill="white")
img_draw_pil.save("../lenna_draw_pillow.png")
img_draw_pil.show()


In [25]:
img_draw_cv = img_cv.copy()
# Rectangle: top-left, bottom-right
cv2.rectangle(img_draw_cv, (50, 50), (200, 200), (90, 95, 3), 3)  
# Line
h, w = img_draw_cv.shape[:2]
cv2.line(img_draw_cv, (0, h -1 ), (w-1, 0), (0, 255, 255), 6)  
# Text
cv2.putText(img_draw_cv, "Lab 1", (60, 230), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (255, 
255, 255), 2)
cv2.imwrite("../outputs/lenna_draw_opencv.png", img_draw_cv)
cv2.imshow("drowed ",img_draw_cv)
cv2.waitKey(0)

-1

***(Why do we write colors as (B, G, R) tuples in OpenCV but use names like "red" in Pillow?)***

there is alot of differance between the tow library because openCV lib is used by the real specialset people but the 
pillow is used for normal programming and the gui things 
so pollow have the channelss (R, G ,B) but you enter it as word then there is another layer convert it to (R,G, B)
but the openCV require directly the (B, G, R ) channels 


In [26]:
#todo : draw a circle around the center of the image using both libraries
#first pilow

img = Image.open("../data/lenna.png")
img_draw_pil = img.copy()
draw = ImageDraw.Draw(img_draw_pil)
# Rectangle: [(x0,y0), (x1,y1)]
w,h = img_draw_pil.size
draw.circle((w/2 + 20 , h/2 + 50), 100, outline="red", width=3)

img_draw_pil.save("../outputs/lenna_draw_pillow.png")
img_draw_pil.show()


In [27]:
img_draw_cv = img_cv.copy()
# Rectangle: top-left, bottom-right
h, w = img_draw_cv.shape[:2]
cv2.circle(img_draw_cv, (int(h/2), int(w/2)), 230, (90, 95, 3), 3)  
cv2.imwrite("../outputs/lenna_draw_opencv.png", img_draw_cv)
cv2.imshow("drowed ",img_draw_cv)
cv2.waitKey(0)

-1